

typedef enum
{
	DICOM_NETWORK_RIS, 
	DICOM_NETWORK_STORAGE, 
	DICOM_NETWORK_PRINTER
} DICOM_NETWORK_ID;

typedef enum
{
	DICOM_PRINTPRIORITY_HIGH, 
	DICOM_PRINTPRIORITY_MED, 
	DICOM_PRINTPRIORITY_LOW
} DICOM_PRINT_PRINTPRIORITY;

typedef enum
{
	DICOM_MEDIATYPE_PAPER, 
	DICOM_MEDIATYPE_CLEARFILM, 
	DICOM_MEDIATYPE_BLUEFILM
} DICOM_PRINT_MEDIUMTYPE;

typedef enum
{
	DICOM_FILMDESTINATION_MAGAZINE, 
	DICOM_FILMDESTINATION_PROCESSOR
} DICOM_PRINT_FILMDESTINATION;

typedef enum
{
	DICOM_FILMORIENTATION_PORTRAIT, 
	DICOM_FILMORIENTATION_LANDSCAPE
} DICOM_PRINT_FILMORIENTATION;

typedef enum
{
	DICOM_FILMSIZEID_8INX10IN, 
	DICOM_FILMSIZEID_10INX12IN,
	DICOM_FILMSIZEID_10INX14IN,
	DICOM_FILMSIZEID_11INX14IN,
	DICOM_FILMSIZEID_14INX14IN,
	DICOM_FILMSIZEID_14INX17IN,
	DICOM_FILMSIZEID_24CMX24CM,
	DICOM_FILMSIZEID_24CMX30CM
} DICOM_PRINT_FILMSIZEID;

typedef enum
{
	DICOM_MAGNIFICATIONTYPE_REPLICATE, 
	DICOM_MAGNIFICATIONTYPE_BILINEAR, 
	DICOM_MAGNIFICATIONTYPE_CUBIC, 
	DICOM_MAGNIFICATIONTYPE_NONE
} DICOM_PRINT_MAGNIFICATIONTYPE;

typedef enum
{
	DICOM_POLARITY_NORMAL, 
	DICOM_POLARITY_REVERSE
} DICOM_PRINT_POLARITY;
