#ifndef _PANAGLOBAL_H_
#define _PANAGLOBAL_H_

#include "Panaskin.h"

PANASKIN_API int PanaMessageBox(LPCTSTR lpszText, UINT nType = MB_OK,
								 UINT nIDHelp = 0 );

PANASKIN_API int PanaMessageBox(LPCTSTR lpszText, LPCTSTR lpszCaption, 
								 UINT nType = MB_OK);

PANASKIN_API void ShowWaiting(int i, LPCTSTR lpszText);

enum PASK_OPERATIONTYPE
{
	PASK_OPERATION_TYPE_NONE = 0,
		PASK_OPERATION_TYPE_BIOPSY,
		PASK_OPERATION_TYPE_CRYOTHERAPY,
		PASK_OPERARION_TYPE_BRACHYTHERAPY,
		PASK_OPERATION_TYPE_OZONETHERAPY,
		PASK_OPERATION_TYPE_TPS,
		PASK_OPERATION_TYPE_REVIEW
};

enum PASK_DEVICE_TYPE{
	PASK_DEVICE_IGS_MF = 1,
	PASK_DEVICE_IGS_CP
};


PANASKIN_API void SetDeviceType(PASK_DEVICE_TYPE type);

#endif //_PANAGLOBAL_H_