//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PanaSkin.rc
//
#define IDB_BITMAP_DLGSKIN              8998
#define IDB_BITMAP_MENUSKIN             8999
#define IDB_BITMAP_TITLE_SKIN           9000
#define IDB_BITMAP_TOOL_TARGET          9001
#define IDC_STATIC_PANA_MSG             9002
#define IDB_BITMAP_TOOL_BROWSEIMAGE     9003
#define IDB_BITMAP_TOOL_CAMERA          9004
#define IDB_BITMAP_TOOL_CAPTURE         9005
#define IDB_BITMAP_TOOL_COMPAREIMAGE    9006
#define IDB_BITMAP_TOOL_MEASURE         9007
#define IDB_BITMAP_TOOL_MOVECAMERA      9008
#define IDB_BITMAP_TOOL_PATIENTTABLE    9009
#define IDB_BITMAP_TOOL_SYSTEM          9010
#define IDB_BITMAP_TOOL_SKIN            9011
#define IDB_BITMAP_MAIN_SKIN            9012
#define IDB_BITMAP_PANAL_SKIN           9013
#define IDB_BITMAP_BTN_LEFTROUND        9014
#define IDB_BITMAP_BTN_NORMAL           9015
#define IDB_BITMAP_BTN_RIGHTROUND       9016
#define IDB_BITMAP_PROBE_FRAME          9017
#define IDB_BITMAP_SEPRATE              9018
#define IDB_BITMAP_BTN_SWAP2            9019
#define IDB_BITMAP_BTN_CYCLE            9020
#define IDB_BITMAP_BTN_LOAD             9021
#define IDB_BITMAP_BTN_ORIENT1          9022
#define IDB_BITMAP_BTN_ORIENT2          9023
#define IDB_BITMAP_BTN_ORIENT3          9024
#define IDB_BITMAP_BTN_POSITION1        9025
#define IDB_BITMAP_BTN_POSITION2        9026
#define IDB_BITMAP_BTN_PRESCAN          9027
#define IDB_BITMAP_BTN_PRESCANSCAN      9028
#define IDB_BITMAP_BTN_SCAN             9030
#define IDB_BITMAP_BTN_STOP             9031
#define IDB_BITMAP_BTN_SWAP1            9032
#define IDB_BITMAP_BTN_ARROW            9033
#define IDB_BITMAP_SCAN_FRAME           9034
#define IDB_BITMAP_BTN_CYCLESTOP        9035
#define IDB_BITMAP_BTN_ARROW_DOWN       9036
#define IDB_BITMAP_TIME_SKIN            9037
#define IDB_BITMAP_INFO_SKIN            9038
#define IDB_BITMAP_PROBE_VISABLE        9039
#define IDB_BITMAP_BASE_VISABLE         9040
#define IDB_BITMAP_BTN_NEXT             9041
#define IDB_BITMAP_BTN_PRE              9042
#define IDB_BITMAP_BTN_SERIES           9043
#define IDB_BITMAP_BTN_MRICONTROL       9044
#define IDB_BITMAP_BTN_PATIENT          9045
#define IDB_BITMAP_DLG_LOGIN_SKIN       9046
#define IDB_BITMAP_BTN_QUIT             9047
#define IDB_BITMAP_BTN_APPLICATION      9048
#define IDB_BITMAP_BTN_CONFIG           9049
#define IDB_BITMAP_BTN_PATIENTDB        9050
#define IDB_BITMAP_BTN_TOOLS            9051
#define IDB_BITMAP_BTN_TPS              9052
#define IDB_BITMAP_BTN_LOGIN_SELECTED_FRAME 9053
#define IDB_BITMAP_BTN_LOGIN_SELECTED   9054
#define IDB_BITMAP_SCROLLBAR            9055
#define IDB_BITMAP_BTN_PUSHADD          9056
#define IDB_BITMAP_BTN_PUSHDEL          9057
#define IDB_BITMAP_BTN_SCROLL           9058
#define IDB_BITMAP_BTN_CONFIG2          9059
#define IDB_BITMAP_DLGSKIN2             9060
#define IDB_BITMAP_DLG_WIZARDSKIN       9061
#define IDB_BITMAP_BTN_WIZARD_PRE       9062
#define IDB_BITMAP_BTN_WIZARD_QUIT      9063
#define IDB_BITMAP_BTN_WIZARD_SELECTED  9064
#define IDB_BITMAP_BTN_WIZARD_SELECTEDARROW 9065
#define IDB_BITMAP_BTN_WIZARD_UNSELECTED 9066
#define IDB_BITMAP_BTN_IMAGE_FIRST      9067
#define IDB_BITMAP_BTN_IMAGE_PRE        9068
#define IDB_BITMAP_BTN_IMAGE_3D         9069
#define IDB_BITMAP_BTN_IMAGE_LAST       9070
#define IDB_BITMAP_BTN_IMAGE_MAX        9071
#define IDB_BITMAP_BTN_IMAGE_NEXT       9072
#define IDB_BITMAP_HEADERCTRL_SKIN      9073
#define IDR_PNG1                        9075
#define IDB_BITMAP1                     9076
#define IDB_BITMAP_BTN_PAUSE            9077
#define IDB_BITMAP_BTN_CONFIG1          9078
#define IDB_BITMAP_BTN_TPS2             9079
#define IDB_BITMAP_BTN_APPLICATION2     9080
#define IDB_BITMAP_BTN_PATIENTDB2       9081
#define IDB_BITMAP_BTN_TOOLS2           9082
#define IDB_BITMAP_LOGIN_SEPRATE        9084
#define IDB_BITMAP_BTN_WIZARD_SELECTEDFAIL 9085
#define IDR_PNG_DOT                     9086
#define IDR_PNG_0                       9087
#define IDR_PNG_1                       9088
#define IDR_PNG_2                       9089
#define IDR_PNG_3                       9090
#define IDR_PNG_4                       9091
#define IDR_PNG_5                       9092
#define IDR_PNG_6                       9093
#define IDR_PNG_7                       9094
#define IDR_PNG_8                       9095
#define IDR_PNG_9                       9096
#define IDR_BITMAP_LOVEFLAG             9097
#define IDB_BITMAP_BTN_BOTHROUND        9098
#define IDR_BITMAP_TAB_SERIES           9099
#define IDR_BITMAP_TAB_PATIENT          9100
#define IDR_BITMAP_TPS_BK               9101
#define IDR_BITMAP_BTN_BOTHROUND_INVERT 9102
#define IDR_BITAMP_BTN_RIGHTROUND_INVERT 9103
#define IDR_BITMAP_BTN_TOPWND           9104
#define IDR_BITMAP_BTN_IMAGE1           9105
#define IDR_BITMAP_BTN_IMAGE2           9106
#define IDR_BITMAP_BTN_IMAGE3           9107
#define IDR_PNG_TPS_BTN_EVALUATE        9113
#define IDR_PNG_TPS_BTN_BK              9114
#define IDR_PNG_TPS_BTN_SAVE            9115
#define IDR_PNG_TPS_BTN_PROBE           9116
#define IDR_PNG_TPS_BTN_OPEN            9117
#define IDB_BITMAP_DLGSKIN_MASK         9118
#define IDB_BITMAP_DLGSKIN2_MASK        9119
#define IDB_BITMAP_WARNING              9121
#define IDB_BITMAP_ERROR                9122
#define IDB_BITMAP_INFORMATION          9123
#define IDR_BITMAP_PROTOCAL             9124
#define IDB_BITMAP_CHECK_FLAG           9125
#define IDD_DLG_MSGBOX                  9126
#define IDC_STATIC_WAITING              9129
#define IDR_BITMAP_MRI_OPTION           9130
#define IDD_DLG_WAITING                 9132
#define IDD_DLG_NULL                    9133
#define IDR_PNG_VIEW1                   9133
#define IDR_PNG_VIEW2                   9134
#define IDR_PNG_VIEW3                   9135
#define IDR_PNG_VIEW4                   9136
#define IDB_BITMAP_DLG_WIZARDSKINCT     9137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9138
#define _APS_NEXT_COMMAND_VALUE         9129
#define _APS_NEXT_CONTROL_VALUE         9130
#define _APS_NEXT_SYMED_VALUE           9129
#endif
#endif
