//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tps.rc
//
#define IDR_MAINFRAME                   3999
#define IDC_BUTTON_MENU_FILE            4000
#define IDC_BUTTON_MENU_HELP            4001
#define IDC_BUTTON_PROBE_VOLUME         4002
#define IDD_DIALOG_CONTROL              4003
#define IDC_BUTTON_APPLY                4004
#define IDC_BUTTON_MODAL_VOLUME         4005
#define IDD_DIALOG_DISPLAY              4006
#define IDD_DIALOG_2DVIEW               4007
#define IDD_DIALOG_3DVIEW               4008
#define IDC_TOOL_REGION                 4009
#define IDI_TRACER_ADD                  4010
#define IDI_TRACER_CLEAR                4011
#define IDI_TRACE_FLAG1                 4012
#define IDI_TRACE_FLAG                  4013
#define IDC_PROP3D_LIST                 4014
#define IDC_TRACERPROP_PLACEHODER       4015
#define IDC_PROBEPROP_PLACEHODER        4016
#define IDC_BMP_LOADIMAGE               4017
#define IDC_BMP_SAVEIMAGE               4018
#define IDB_BITMAP_OPENIMAGE            4019
#define IDC_BMP_CREATETOOL              4020
#define IDB_BITMAP_TOOL                 4021
#define IDC_BMP_EVALUATE                4022
#define IDB_BITMAP_CREATEMODAL          4023
#define IDB_BITMAP_EVALUATE             4024
#define IDI_PRE_IMAGE                   4025
#define IDI_NEXT_IMAGE                  4026
#define IDB_TOOL_TREE_IMAGE             4027
#define IDC_IMAGEPROP_PLACEHODER        4028
#define IDR_POPUPMENU_IMAGE             4029
#define IDC_MODALPROP_PLACEHODER        4030
#define IDR_POPUPMENU_ZONEGROUP         4031
#define IDD_TRACER_PROPERTY             4032
#define IDR_POPUPMENU_PROBE             4033
#define IDB_BITMAP_SAVEIMAGE            4034
#define IDR_POPUPMENU_EXTERNAL          4035
#define IDB_BITMAP_MEASURE              4036
#define IDB_BITMAP_MEASURE2             4037
#define IDC_ROTATE_BOX                  4038
#define IDC_POSITION_BOX                4039
#define IDI_TOOL_TRANSFORM              4040
#define IDC_PROBE_ROTATE                4041
#define IDI_TOOL_ROTATE                 4042
#define IDC_PROBE_POSITION              4043
#define IDI_TOOL_FORWARD                4044
#define IDC_RATIO_TOOL_TRANSFORM_X      4045
#define IDR_POPUPMENU_FILE              4046
#define IDC_RATIO_TOOL_TRANSFORM_Y      4047
#define IDR_POPUPMENU_ZONE              4048
#define IDC_RATIO_TOOL_TRANSFORM_Z      4049
#define IDR_POPUPMENU_MODAL             4050
#define IDC_PROBE_CONTROL_AXIS_X        4051
#define IDB_TOOL_BACKGROUND2            4052
#define IDC_PROBE_CONTROL_AXIS_Y        4053
#define IDR_POPUPMENU_VIEW              4054
#define IDC_LIST_OPTIONS                4055
#define IDD_DIALOG_PROBE_CONTROL        4056
#define IDC_WORKSPACE                   4057
#define IDC_LIST_PROBE                  4058
#define IDR_MAINMENU                    4059
#define IDB_BITMAP_IMRIFIGURE           4060
#define IDC_LIST_MODAL                  4061
#define IDR_POPUPMENU_VIEW3D            4062
#define IDC_EDIT_VOLUME_RESULT          4063
#define IDR_POPUPMENU_MPR_VIEW          4063
#define IDC_EDIT_DISPLAY_INDEX          4064
#define IDC_IMAGE_BROW_DISP             4065
#define IDC_IMAGE_BROW_CTRL             4066
#define IDC_SLIDER_GREY                 4067
#define IDC_ACTIVE_WND                  4068
#define IDC_CUR_VALUE                   4069
#define IDB_BMP_BACKGROUND              4070
#define IDI_UPANDDOWN                   4071
#define IDI_RIGHTANDLEFT                4072
#define IDI_LEDOFF                      4073
#define IDI_LEDON                       4074
#define IDD_DIALOG_OPTION               4075
#define IDI_UP                          4076
#define IDB_OPTIONS                     4077
#define IDD_IMAGE_PROCESSING            4078
#define IDD_DIALOG_AUTO_TRACE           4079
#define IDC_BUTTON_FIRST_IMAGE          4080
#define IDC_BUTTON_LAST_IMAGE           4081
#define IDC_BUTTON_PRE_IMAGE            4082
#define IDC_BUTTON_NEXT_IMAGE           4083
#define IDC_BUTTON_3D_IMAGE             4084
#define IDC_BUTTON_TOPWND_SHOW          4085
#define IDC_BUTTON_SELECT_IMAGE         4086
#define IDC_BUTTON_CLOSE                4087
#define IDD_DLG_EVALUATE                4088
#define IDD_PROBE_PROPERTY              4089
#define IDD_IMAGE_PROPERTY              4090
#define IDD_MODAL_PROPERTY              4091
#define IDD_IMAGE_BROWSER               4092
#define IDD_DIALOG_MARCHING_CUBE        4093
#define IDD_DIALOG_MPR                  4093
#define IDC_BNT_EVA_RETURN              4094
#define IDD_DIALOG_PROBE_CONTROL1       4094
#define IDC_BNT_EVA_REFRESHLIST         4095
#define IDR_POPUPMENU_DISPLAY_CONTOUR   4096
#define IDR_POPMENU_IMAGE_PROP          4097
#define IDR_POPUPMENU_DISPLAY_SEGENT    4098
#define IDR_POPMENU_ZONE_DELETE         4099
#define IDR_POPMENU_ZONE_PROP           4100
#define IDR_POPMENU_IMAGE_OPEN          4101
#define IDR_POPMENU_PROBE_DELETE        4102
#define IDR_POPMENU_PROBE_PROP          4103
#define IDR_POPMENU_PROBE_BALL_VISIBLE  4104
#define IDR_POPMENU_2DVIEW_DISPLAYAVERAGE 4105
#define IDR_POPUPMENU_2DVIEW_DISPLAY2DTOP 4106
#define IDR_POPUPMENU_DISPLAY_MAX       4107
#define IDR_POPUPMENU_FILE_NEW          4108
#define IDR_POPUPMENU_FILE_OPEN         4109
#define IDR_POPUPMENU_FILE_SAVE         4110
#define IDR_POPUPMENU_FILE_SAVEAS       4111
#define IDR_POPUPMENU_DISPLAY_DISPLAYMEASURE 4112
#define IDR_POPUPMENU_DISPLAY_DELETEMEASURE 4113
#define IDR_POPMENU_ZONEGROUP_DELETE    4114
#define IDR_POPMENU_ZONEGROUP_NEW       4115
#define IDR_POPMENU_ZONEGROUP_CREATEMODAL 4116
#define IDR_POPMENU_ZONEGROUP_RENAME    4117
#define IDR_POPUPMENU_MODAL_VISIBLE     4118
#define IDR_POPUPMENU_MODAL_DELETE      4119
#define IDR_POPUPMENU_MODAL_RENAME      4120
#define IDR_POPUPMENU_MODAL_PROP        4121
#define IDR_POPMENU_ZONEGROUP_TUMOR     4122
#define IDR_POPMENU_ZONEGROUP_ORGAN     4123
#define IDR_POPMENU_ZONEGROUP_SETCOLOR  4124
#define IDR_POPUPMENU_MEASURE_DIS       4125
#define IDR_POPUPMENU_MEASURE_ANGLE     4126
#define IDR_POPMENU_EXPORTTPS_MAIN      4127
#define IDR_POPMENU_EXPORTTPS_SECOND    4128
#define IDR_POPMENU_EXPORTTPS_THIRD     4129
#define IDR_POPMENU_EXPORTTPS_3DIMAGE   4130
#define IDR_POPUPMENU_DISPLAY_RETCAMERA 4131
#define IDR_POPUPMENU_VIEW3D_DISPIMAGE1 4132
#define IDR_POPUPMENU_VIEW3D_DISPIMAGE2 4133
#define IDR_POPUPMENU_VIEW3D_DISPIMAGE3 4134
#define IDR_POPUPMENU_MEASURE_DIS_3D    4135
#define IDR_POPMENU_PROBE_LINE_VISIBLE  4136
#define IDR_POPMENU_ZONE_TRACKPOSITION  4137
#define IDR_POPUPMENU_DISPLAY_RESETWINDOWLEVEL 4138
#define IDR_POPUPMENU_DISPLAY_2DRESETVIEW 4139
#define IDR_POPMENU_PROBE_TIP           4140
#define IDR_POPMENU_PROBE_END           4141
#define IDR_POPMENU_ZONEGROUP_SETDEFAULT 4142
#define IDR_POPMENU_PROBE_UCS           4143
#define IDR_POPMENU_PROBE_COPYUCS       4144
#define IDR_POPMENU_PROBE_MOVE          4145
#define IDR_POPUPMENU_FILE_EXIT         4146
#define IDR_POPUPMENU_DISPLAY_VOLUME    4147
#define IDC_RADIO_X                     4147
#define IDR_POPUPMENU_DISPLAY_MPR       4148
#define IDC_RADIO_Y                     4148
#define IDR_POPMENU_PROBE_MPR           4149
#define IDC_RADIO_Z                     4149
#define IDC_RADIO_TIP                   4150
#define IDR_POPUPMENU_VIEW3D_FLYTO      4150
#define IDC_RADIO_END                   4151
#define IDR_POPUPMENU_VIEW3D_BKCOLOR    4151
#define IDC_RADIO_NONE                  4152
#define IDC_BUTTON_NEW                  4153
#define IDC_BUTTON_DELETE               4154
#define IDC_CHECK1                      4155
#define IDC_CHECK_AUTO                  4155
#define IDC_BUTTON_3D                   4156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4147
#define _APS_NEXT_COMMAND_VALUE         4152
#define _APS_NEXT_CONTROL_VALUE         4157
#define _APS_NEXT_SYMED_VALUE           4147
#endif
#endif
