//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Surgery.rc
//
#define IDR_MANIFEST                    1
#define ID_CMP_CTRL_ASSOCIATE           2
#define IDAPPLY                         3
#define ID_SIMULATE                     3
#define ID_MANUAL_CALI_S1               3
#define ID_CALI_START                   3
#define ID_READ_POS                     3
#define ID_MANUAL_CALI_S2               4
#define ID_CALI_PT                      4
#define ID_APPLY                        5
#define ID_MANUAL_CALI_S3               5
#define ID_CALI_CLEAN                   5
#define ID_MANUAL_CALI_LOAD_BASEINTRACKER 6
#define ID_MANUAL_CALI_LOAD_PHANTOMREF  7
#define ID_MANUAL_CALI                  8
#define ID_MANUAL_CALI_LOAD_IMG         14
#define ID_MANUAL_CALI_LOAD_DB          15
#define ID_MANUAL_CALI_CALI             16
#define IDD_ABOUTBOX                    100
#define IDD_MYABOUTBOX                  100
#define ID_STATUSBAR_PROGRESS           101
#define IDD_COMBINEDAPISAMPLE_DIALOG    102
#define ID_STATUS_SURGERY               102
#define IDR_SURGERY                     103
#define ID_STATUS_PRE_IMAGING           103
#define ID_STATUSBAR_TRACKING_STATUS    104
#define IDC_POINTER                     104
#define ID_STATUSBAR_BASE               105
#define IDC_POINTER_COPY                105
#define ID_STATUSBAR_NEEDLE_PROBE       106
#define IDC_NODROP                      106
#define ID_STATUSBAR_PATIENT_TABLE      107
#define IDD_DLG_FILTER                  108
#define IDR_MAINFRAME                   128
#define IDR_ISPPATTYPE                  129
#define IDD_DLG_CONTROL_VIEW            130
#define IDD_COM_PORT_SETTINGS           131
#define IDD_ROM_FILES                   132
#define IDD_SYSTEM_FEATURES             133
#define IDD_DLG_TRACKING_INFORMATION    134
#define IDD_DLG_TOOL_INFORMATION        135
#define IDD_DLG_CRYOTHERAPY             136
#define IDD_DLG_DISPLAY                 137
#define IDD_DLG_DISPLAY4                138
#define IDD_DLG_SETTING_TRACKINGTYPE    140
#define IDD_DLG_CALI_PROBE              141
#define IDD_DLG_IMG_COORD               142
#define IDR_POP_MENU                    143
#define IDD_DLG_CALI_PROBE_ORI          144
#define IDD_DIG_SIMULATE                146
#define IDD_DLG_PRE_SURGERY_CALI        147
#define IDD_DLG_SURGERY                 148
#define IDD_DLG_MRI_2D_DISPLAY          149
#define IDD_DLG_SPHERE_CENTER           151
#define IDD_DLG_OPTION                  152
#define IDD_DLG_TCP_LISTEN              153
#define IDD_DLG_MRI_OPTIONS             154
#define IDD_DLG_PLAN_OPTION             155
#define IDD_DLG_DISPLAY_CONTROL         156
#define IDD_DLG_DISPLAY_WRAP            157
#define IDD_DLG_SETTING_DISPLAY         158
#define IDD_DLG_SURGICAL_PLANNING       159
#define IDD_DLG_PROTOCOL_DEFINE         160
#define IDD_DLG_SCANNER_CONTROL         161
#define IDD_DLG_BASESELECTION           162
#define IDD_DLG_BASECALIBRATION         163
#define IDD_DLG_NAVIGATION_MODE         164
#define IDD_DLG_STAGE_OF_THERAPY        165
#define IDD_DLG_SERGERY                 166
#define IDD_DLG_SERGERY_CRYOTHERAPY     166
#define IDR_MAINFRAME_SURGERY_EN        172
#define IDD_DLG_TRACKING_STATUS         173
#define IDD_DLG_PROBE_SETTING           175
#define IDD_DLG_PROBE_CRY_SETTING       175
#define IDD_DLG_BROWSE                  177
#define IDD_DLG_IMAGE_DISPLAY           178
#define IDD_DLG_CALIRESULT              180
#define IDD_DLG_TABLESELECTION          181
#define IDD_DLG_MRI_BROWSE              182
#define IDD_DLG_CRYO_PLANNING           183
#define IDD_DLG_COMPARE_DISP            185
#define IDD_DLG_COMPARE_CONTROL         186
#define IDD_PATIENT_INFOR               187
#define IDR_TOOLBAR1                    195
#define IDB_MENUBAR_NORM                197
#define IDD_CMD_BAR                     198
#define IDB_BITMAP1                     200
#define IDB_BITMAP2                     201
#define IDB_BITMAP3                     202
#define IDB_BITMAP4                     203
#define IDR_DEBUG                       204
#define IDB_TARGET                      206
#define IDB_MEASURE                     207
#define IDB_BASE                        208
#define IDB_CAMMOVE                     209
#define IDB_IMGDISPLAY                  210
#define IDB_IMGCOMP                     211
#define IDB_MEASURE2                    212
#define IDB_TARGET2                     213
#define IDB_FULLDISPLAY                 214
#define IDI_LEDON                       215
#define IDI_LEDOFF                      216
#define IDI_HELP                        217
#define IDD_DLG_MANUAL_CALIBRATION      218
#define IDD_DLG_EM_MANUAL_CALIBRATION   218
#define IDC_EDIT_PATIENT_ID             219
#define IDB_SCREENSNAP                  219
#define IDC_EDIT_STUDY_ID               219
#define IDI_MAINFRAME                   220
#define IDD_SHEET_CRY                   223
#define IDD_DLG_MOVE_PT                 223
#define IDD_DLG_TAB_CRY                 224
#define IDD_DLG_SERIES                  225
#define IDD_DLG_PROBE                   226
#define IDD_DLG_PATIENT                 227
#define IDC_EDIT_PATIENT_NAME           228
#define IDD_DLG_TPS                     228
#define IDC_EDIT_STUDY_TIME             228
#define IDD_DLG_TITLE                   230
#define IDR_SYS                         231
#define IDR_PROTOCOL                    232
#define IDD_DLG_WIZARD                  233
#define IDC_EDIT_PATIENT_DESCRIPTION    235
#define IDC_EDIT_STUDY_DESCRIPTION      235
#define IDC_EDIT_AGE                    240
#define IDC_EDIT_WEIGHT                 244
#define IDC_EDIT_OPERATOR               244
#define IDB_TRACKING                    247
#define IDC_COMBO_SEX                   248
#define IDC_COMBO_LANDMARK_POS          248
#define IDB_T_BIO                       249
#define IDC_COMBO_BODYPART              249
#define IDB_T_CRYO                      250
#define IDC_COMBO_LYING_POS             250
#define IDB_T_BRAC                      251
#define IDC_COMBO_BODY_ENTRY            251
#define IDB_T_OZON                      252
#define IDC_COMBO_RADIOLOGIST           252
#define IDB_T_XINAO                     253
#define IDC_COMBO_REF_PHY               253
#define IDB_TRACKING2                   254
#define IDD_DLG_CALI_MODE_SEL           255
#define IDB_WT_BIO                      257
#define IDB_WT_CRYO                     259
#define IDB_WT_BRAC                     260
#define IDB_WT_OZON                     261
#define IDB_WIZ_CAM                     263
#define IDB_WIZ_CAM_DONE                264
#define IDB_WIZ_CAM_FAIL                265
#define IDB_WIZ_CAM_ING                 266
#define IDB_WIZ_BAS                     268
#define IDB_WIZ_BAS_DONE                269
#define IDB_WIZ_BAS_FAIL                270
#define IDB_WIZ_BAS_ING                 271
#define IDB_WIZ_CAL                     272
#define IDB_WIZ_CAL_DONE                273
#define IDB_WIZ_CAL_FAIL                274
#define IDB_WIZ_CAL_ING                 275
#define IDB_WIZ_MRI                     276
#define IDB_WIZ_MRI_DONE                277
#define IDB_WIZ_MRI_FAIL                278
#define IDB_WIZ_MRI_ING                 279
#define IDB_WIZ_PAT_ING                 280
#define IDB_WIZ_PAT                     281
#define IDB_WIZ_PAT_DONE                282
#define IDB_WIZ_PAT_FAIL                283
#define IDD_DLG_MSGS                    284
#define IDB_WIZ_BOTTOM                  286
#define IDB_WIZ_BG2                     287
#define IDB_EXIT                        289
#define IDB_EXIT2                       290
#define IDB_EXIT3                       291
#define IDB_EXIT4                       292
#define IDB_EXIT5                       293
#define IDB_EXIT11                      294
#define IDB_EXIT10                      295
#define IDB_EXIT20                      296
#define IDB_EXIT21                      297
#define IDB_EXIT30                      298
#define IDB_EXIT31                      299
#define IDD_DLG_MSGBOX                  300
#define IDD_DLG_TPS_DISP                301
#define IDD_DLG_PROBE_BIO_SETTING       302
#define IDD_DLG_CALI_PT                 303
#define IDB_MOVEPT                      304
#define IDD_DLG_MOVE_PT2                306
#define IDD_DLG_TIME                    307
#define IDR_PROBE                       308
#define IDD_DLG_MAIN                    309
#define IDR_SYS_CP                      309
#define IDD_DLG_MRI_WRAP                310
#define IDD_DLG_DICOM_SRV               311
#define IDD_DLG_INFO_HIST               312
#define IDD_DLG_COMPARE_FRAME           313
#define IDB_LOGO                        314
#define IDR_PNG_LOGO1                   315
#define IDR_PNG1                        316
#define IDR_PNG_INFO_PROMPT             317
#define IDR_PNG_BASE4                   318
#define IDR_PNG_BASE1                   319
#define IDR_PNG_BASE2                   320
#define IDR_PNG_BASE3                   321
#define IDC_TARGET                      323
#define IDD_DLG_MY_MSG_BOX              324
#define IDB_ICONWARNING                 327
#define IDR_LOGO                        328
#define IDD_DLG_SETUP_LEGEND            329
#define IDD_DLG_MOVE_PT1                330
#define IDR_PNG_BTN_DOWN                331
#define IDD_DLG_NAVIGATE                331
#define IDR_PNG_BTN_LEFT                332
#define IDR_PNG_BTN_RIGHT               333
#define IDR_PNG_BTN_UP                  334
#define IDR_PNG_BTN_NORMAL              335
#define IDR_PNG_BROW_F9                 336
#define IDR_PNG_BROW_F1                 337
#define IDR_PNG_BROW_F2                 338
#define IDR_PNG_BROW_F3                 339
#define IDR_PNG_BROW_F4                 340
#define IDR_PNG_BROW_F5                 341
#define IDR_PNG_BROW_F6                 342
#define IDR_PNG_BROW_F7                 343
#define IDR_PNG_BROW_F8                 344
#define IDR_PNG_QUIT                    345
#define IDR_PNG_BLACKGROUND             346
#define IDB_PNG_TOOL_CAPTURE            347
#define IDC_CUR_MEASURE                 349
#define IDD_DIALOG_SERIES_SELECT        350
#define IDD_DLG_WAITING                 351
#define IDB_BITMAP_SEPRATE1             351
#define IDD_DLG_TPS_CTRL                352
#define IDD_DLG_SCANNER_CONTROL_OPTION  353
#define IDD_DLG_IMPORT_PATIENT          354
#define IDD_DLG_CALIBRATE_IGS_CP        355
#define IDD_DLG_TRACKER                 356
#define IDR_PNG_TRACKER_BASE            356
#define IDD_DLG_TARGETING               357
#define IDR_PNG_TARGETING               357
#define IDD_DLG_USDISPLAY               358
#define IDD_DLG_TRACKING_DISPLAY        359
#define IDD_DLG_OPTIC_MANUAL_CALIBRATION 360
#define IDD_DLG_USDISPLAY_SLIDER        361
#define IDD_DLG_FUSION                  361
#define IDR_PNG_GENERAL_BK              362
#define IDC_CUR_LR                      363
#define IDC_INITIALIZE_SYSTEM           1000
#define IDC_EDT_SYSTEM_INFO             1002
#define IDC_ACTIVATE_PORTS              1002
#define IDC_NO_ACTIVE_PORTS             1003
#define IDC_TRACKING_BUT                1003
#define IDC_NO_WIRELESS_PORTS           1004
#define IDC_TRACKING_LIST               1004
#define IDC_CHK_PORT_ENABLE             1004
#define IDC_NO_WIRELESS_ACTIVE_PORTS    1005
#define IDC_TRACKING_TX                 1005
#define IDC_CHK_PORT_INIT               1005
#define IDC_TRACKING_BX                 1006
#define IDC_CRYO_TRACKING               1006
#define IDC_FRAME1                      1007
#define IDC_FRAME_NO                    1008
#define IDC_FRAME2                      1008
#define IDC_FRAME3                      1009
#define IDC_FRAME_LABEL                 1010
#define IDC_HELPERCTRL1                 1011
#define IDC_TRACKING_REPORT_OOV         1012
#define IDC_SYSTEMMODE                  1013
#define IDC_RADIO_ABBROBOT              1013
#define IDC_RADIO_NDI                   1014
#define IDC_CHECK_PHANTOM               1014
#define IDC_BTN_PROBE_COLLECT           1015
#define IDC_RESET_SYSTEM                1016
#define IDC_BTN_CALI_PROBE              1016
#define IDC_BTN_PROBE_APPLY             1016
#define IDC_COM_PORTS                   1017
#define IDC_BTN_CALI_PROBE_ORI          1017
#define IDC_HARDWARE                    1018
#define IDC_BTN_PROBE_REDO              1018
#define IDC_BTN_CALI_IMPORT             1018
#define IDC_BTN_PROBE_CANCEL            1019
#define IDC_PROBE_COLOR                 1019
#define IDC_RESET                       1019
#define IDC_PROBE_CALI_INST2            1020
#define IDC_BTN_CALI_EXPORT             1020
#define IDC_MRI_LIST                    1021
#define IDC_BTN_ATTACH_PROBE            1021
#define IDC_BTN_PROBE_EXPORT            1022
#define IDC_BTN_SET_COORD_START_COLLECT 1022
#define IDC_BTN_NEW_PROBE               1022
#define IDC_LAB_INSTRUCTION             1023
#define IDC_BTN_DETACH_PROBE            1023
#define IDC_BTN_SET_COORD_START_REDO    1024
#define IDC_PROBE_TIP_X                 1024
#define IDC_PROBE_TIP_Y                 1025
#define ID_STATIC                       1025
#define IDC_CALI_COLLECT_INST           1025
#define IDC_BTN_SET_COORD_START_APPLY   1026
#define IDC_PROBE_TIP_Z                 1026
#define IDC_EDIT_MRI_SERIES_NEW_CENTER_X 1027
#define IDC_PROBE_TIP_VX                1027
#define IDC_EDIT_MRI_SERIES_NEW_CENTER_Y 1028
#define IDC_PROBE_TIP_VY                1028
#define IDC_EDIT_MRI_SERIES_NEW_CENTER_Z 1029
#define IDC_PROBE_TIP_VZ                1029
#define IDC_EDIT_MRI_SERIES_NEW_XAXIS_X 1030
#define IDC_EDIT_IMAGE_VERTEX_AX        1031
#define IDC_EDIT_IMAGE_VERTEX_AY        1032
#define IDC_BAUD_RATE                   1033
#define IDC_PORT_LISTING                1033
#define IDC_EDIT_MRI_SERIES_NEW_XAXIS_Y 1033
#define IDC_PARITY                      1034
#define IDC_PORT                        1034
#define IDC_EDIT_MRI_SERIES_NEW_XAXIS_Z 1034
#define IDC_DATA_BITS                   1035
#define IDC_ROM_FILE                    1035
#define IDC_EDIT_MRI_SERIES_NEW_YAXIS_X 1035
#define IDC_STOP_BITS                   1036
#define IDC_BROWSE                      1036
#define IDC_EDIT_MRI_SERIES_NEW_YAXIS_Y 1036
#define IDC_EDIT_MRI_SERIES_NEW_YAXIS_Z 1037
#define IDC_BROWSE_PT_SROM              1037
#define IDC_EDIT_IMAGE_VERTEX_AZ        1038
#define IDC_EDIT_IMAGE_VERTEX_BX        1039
#define IDC_EDIT_IMAGE_VERTEX_BY        1040
#define IDC_TOOL_TYPE                   1041
#define IDC_EDIT_IMAGE_VERTEX_BZ        1041
#define IDC_MANUF_ID                    1042
#define IDC_EDIT_IMAGE_VERTEX_DX        1042
#define IDC_TOOL_REV                    1043
#define IDC_EDIT_IMAGE_VERTEX_DY        1043
#define IDC_EDIT_IMAGE_VERTEX_DZ        1044
#define IDC_SERIAL_NO                   1045
#define IDC_CBO_IMGS                    1045
#define IDC_PORT_HANDLES                1046
#define IDC_EDIT_REL_DIST               1046
#define IDC_PORT_INIT                   1047
#define IDC_TOOL_PROBE_LENGTH           1047
#define IDC_BTN_SET_COORD_START_CHANGE  1047
#define IDC_PORT_ENABLED                1048
#define IDC_TOOL_PROBE_RADIUS           1048
#define IDC_RADIO_CHANGE_TYPE           1048
#define IDC_VERSION_INFO                1049
#define IDC_RADIO_CHANGE_TYPE2          1049
#define IDC_CBO_PROBE                   1049
#define IDC_RADIO_CHANGE_TYPE3          1050
#define IDC_CBO_PROBE_TYPE              1050
#define IDC_CBO_TARGET                  1050
#define IDC_EDIT_BIRTHDATE              1050
#define IDC_EDIT_MR_NO                  1050
#define IDC_RADIO_CHANGE_TYPE4          1051
#define IDC_CBO_REAL_PROBE              1051
#define IDC_ACTIVE_PORTS                1052
#define IDC_IMG_CALI_PROBE              1052
#define IDC_PASSIVE_PORTS               1053
#define IDC_SIMU_RADIUS                 1053
#define IDC_EDIT_IMAGE_ROTATE_VX        1054
#define IDC_SIMU_TRANSPARENCY           1054
#define IDC_CALI_STEP_INST              1054
#define IDC_EDIT_IMAGE_ROTATE_VY        1055
#define IDC_CALI_COLLECT                1055
#define IDC_EDIT_IMAGE_ROTATE_VZ        1056
#define IDC_CALI_COLLECT_REDO           1056
#define IDC_ACTIVE_WIRELESS             1057
#define IDC_EDIT_ROTATE_DEGREE          1057
#define IDC_CALI_NEXT_STEP              1057
#define IDC_TIP_DETECTION               1058
#define IDC_CALI_DETAIL_INST            1058
#define IDC_SURGERY_INST                1059
#define IDC_CALI_GET_PT_POSITION        1059
#define IDC_SYSTEM_INFO_FRAME           1060
#define IDC_PANEL                       1060
#define IDC_CALI_SKIP                   1060
#define IDC_ACTIVE_PORTS_LBL            1061
#define IDC_PRE_CALI_PROBE              1061
#define IDC_TIP_DETECTION_LBL           1062
#define IDC_PRE_CALI_IMAGES             1062
#define IDC_IPADDRESS1                  1062
#define IDC_PASSIVE_PORTS_LBL           1063
#define IDC_PT_ROM_FILE                 1063
#define IDC_CALI_CAL_CIRCLE             1063
#define IDC_ACTIVE_WIRELESS_LBL         1064
#define IDC_CHK_TRACK_PT                1064
#define IDC_CALI_BASE                   1064
#define IDC_CHK_BASE0                   1065
#define IDC_CALI_CLEAN_PHANTOM_CENTER   1065
#define IDC_CHK_BASE1                   1066
#define IDC_CHK_BASE2                   1067
#define IDC_CHK_GETPOS                  1068
#define IDC_FRM_2D                      1069
#define IDC_LBL_INFO                    1071
#define IDC_CHK_FREEZE_IMG              1072
#define IDC_CBO_CIRCLES                 1072
#define IDC_EDT_X                       1073
#define IDC_ICEBALL_RADIUS              1073
#define IDC_EDT_Y                       1074
#define IDC_ICEBALL_TRANSPARENCY        1074
#define IDC_EDT_Z                       1075
#define IDC_EDT_REPLAY_FOLDER           1075
#define IDC_SERIES_BROWN                1076
#define IDC_EDT_MRI_PLAY_GAP            1077
#define IDC_ROM_LABEL                   1078
#define IDC_MRI_PLAY_LOAD               1078
#define IDC_EDT_ATTACHED_PROBE          1078
#define IDC_ROM_LABEL2                  1079
#define IDC_EDT_ATTACHED_TRACKTOOL      1079
#define IDC_RADIO_BASE0                 1080
#define IDC_RADIO_BASE1                 1081
#define IDC_CMD_UPDATE_MRI_POSITION     1081
#define IDC_RADIO_BASE2                 1082
#define IDC_CMD_UPDATE_BOX_POSITION     1082
#define IDC_LBL_PROBE_TYPE_INFO         1083
#define IDC_CMD_START_TRACKING          1083
#define IDC_EDT_MRI_STORAGE_FOLDER      1084
#define IDC_CMD_MEASUREMENT             1084
#define IDC_MRI_STORAGE_BROWN           1085
#define IDC_CMD_UPDATE_PT_POSITION      1085
#define IDC_EDT_MRI_PLAY_FOLDER         1086
#define IDC_CMD_BASE_SELECTION          1086
#define IDC_MRI_PLAY_BROWN              1087
#define IDC_CMD_CAMER_MOVE              1087
#define IDC_CHK_SAVE_MRI                1088
#define IDC_CMD_COMPARE                 1088
#define IDC_EDT_ICEBALL_OFFSET          1089
#define IDC_CMD_SCREEN_CAP              1089
#define IDC_CMD_MOVE_PT                 1090
#define IDC_CHK_3D                      1091
#define IDC_CMD_MOVE_PT2                1091
#define IDC_GB_CTRL                     1092
#define IDC_CHK_DISP_SETTING_SHOW_CTL   1093
#define IDC_LAL_MIN                     1094
#define IDC_LAL_MAX                     1095
#define IDC_CBO_MODELS                  1098
#define IDC_SLDR_MODEL_TRANSPARENCY     1099
#define IDC_LBL_MODEL_TRANSPARENCY      1100
#define IDC_LBL_MODEL_TRANSPARENCY_MIN  1101
#define IDC_LBL_MODEL_TRANSPARENCY_MAX  1102
#define IDC_CHK_CLICK_TARGET_MESH       1103
#define IDC_CHK_CLICK_TARGET_MRI        1104
#define IDC_SLDR_PROBE_ROTATE_POSITION  1105
#define IDC_SLDR_PROBE_ROTATE_X         1106
#define IDC_SLDR_PROBE_ROTATE_Y         1107
#define IDC_BTN_TARGET_CONNECT_VPROBE   1108
#define IDC_BTN_TARGET_CONNECT_PROBE    1109
#define IDC_CHK_CONTROL_MRI_SCANNER     1109
#define IDC_SLDR_PROBE_MOVE_TARGET      1110
#define IDC_LBL_TRACK_DIR_LR            1110
#define IDC_BTN_NEW_VPROBE              1111
#define IDC_LBL_TRACK_DIR_SI            1111
#define IDC_OPERATION_MODE_ONSITE       1111
#define IDC_BTN_PROBE_NEW               1111
#define IDC_BTN_DELETE_VPROBE           1112
#define IDC_OPERATION_MODE_OFFSITE      1112
#define IDC_CHK_SHOW_MAX                1112
#define IDC_LBL_TRACK_DIR_LR_ANGLE      1112
#define IDC_BTN_PROBE_DELETE            1112
#define IDC_BTN_DELETE_VTARGET          1113
#define IDC_LBL_TRACK_DIR_SI_ANGLE      1113
#define IDC_CBO_PROTOCOL_BODY_PART      1113
#define IDC_BTN_TARGET_DELETE           1113
#define IDC_CHK_SERIES_DISPLAY          1113
#define IDC_BTN_SIMULATE                1114
#define IDC_CBO_PROTOCOLS               1114
#define IDC_BTN_PROBE_FINISHED          1114
#define IDC_SLDR_MOVE_VPROBE            1115
#define IDC_CMD_LOAD_PROTOCOL           1115
#define IDC_BTN_PROBE_SIMULATE          1115
#define IDC_WIRELESS                    1116
#define IDC_BTN_MESH_COLOR              1116
#define IDC_CMD_PRE_SCAN                1116
#define IDC_BTN_PROBE_TO_IMAGE          1116
#define IDC_DIAGNOSTICS_PENDING         1117
#define IDC_CMD_SCAN                    1117
#define IDC_BTN_MANUAL_CALI             1117
#define IDC_ACCEPT                      1118
#define IDC_CMD_PRESCAN_SCAN            1118
#define IDC_FRM_SCANNER_CONTROL         1119
#define IDC_CMD_TEST_BAR                1119
#define IDC_PARTNUMBER                  1120
#define IDC_CMD_MODIFY_PROTOCOL         1120
#define IDC_PROT_DEFINE_CHK_CYCLE       1121
#define IDC_CMD_SCAN_PAUSE              1121
#define IDC_PROT_DEFINE_EDT_DURATION    1122
#define IDC_CMD_SCAN_STOP               1122
#define IDC_WIRELESS_NOTE               1123
#define IDC_CMD_PROTOCOL                1123
#define IDC_BTN_PROBE_SIMULATE2         1124
#define IDC_CMD_RADIO_PROBE             1125
#define IDC_CMD_RADIO_LAST_POS          1126
#define IDC_CMD_RADIO_PLANE1            1127
#define IDC_CMD_RADIO_PLANE2            1128
#define IDC_CMD_RADIO_PLANE3            1129
#define IDC_CMD_CHK_SWAP                1130
#define IDC_CMD_CHK_SWAP_ON             1130
#define IDC_RADIO_SC_LOC_PROBE          1131
#define IDC_RADIO_SC_LOC_LAST_SCAN      1132
#define IDC_RADIO_SC_LOC_PLANE1         1133
#define IDC_RADIO_SC_LOC_PLANE2         1134
#define IDC_RADIO_SC_LOC_PLANE3         1135
#define IDC_CMD_CHK_ADVANCE             1136
#define IDC_CMD_CHK_CYCLE               1137
#define IDC_TXT_MRI_SCANNER_PORT        1138
#define IDC_CMD_CHK_SWAP2               1138
#define IDC_CMD_CHK_SWAP_OFF            1138
#define IDC_RICHEDIT1                   1140
#define IDC_RICHEDIT_OUTPUT             1140
#define IDC_REDT_MSGS                   1140
#define IDC_TEMPERATURE_NOTE            1141
#define IDC_PROGRESS_SCAN               1142
#define IDC_TXT_OFFSET                  1143
#define IDC_LABL_OFFSET                 1144
#define IDC_LABL_OFFSET2                1145
#define IDC_CMD_SET_LOC_OFFSET          1146
#define IDC_CHK_SWAP                    1147
#define IDC_RADIO_NORMAL                1148
#define IDC_RADIO_CALIBRATION_NOW       1149
#define IDC_RADIO_SHARP_L1              1149
#define IDC_RADIO_CALIBRATION_USELAST   1150
#define IDC_RADIO_ONSITE                1150
#define IDC_RADIO_SHARP_L2              1150
#define IDC_RADIO_OFFSITE               1151
#define IDC_RADIO_PRE_IMAGING           1151
#define IDC_RADIO_SHARP_L3              1151
#define IDC_RADIO_SURGERY               1152
#define IDC_TRACKINGSTATUS_BASE         1152
#define IDC_RADIO_SHARP_L4              1152
#define IDC_TRACKINGSTATUS_NEEDLE_OR_PROBE 1153
#define IDC_RADIO_SPINE_SMOOTH          1153
#define IDC_TRACKINGSTATUS_PATIENT_TABLE 1154
#define IDC_RADIO_MRA                   1154
#define IDC_BTN_TARGET                  1155
#define IDC_RADIO_SMOOTH_L1             1155
#define IDC_COMBO_PLANNING_ID           1156
#define IDC_RADIO_SMOOTH_L2             1156
#define IDC_BTN_TARGET_DEL              1157
#define IDC_RADIO_SMOOTH_L3             1157
#define IDC_ADVANCED_OPTION             1158
#define IDC_RADIO_NONE                  1158
#define IDC_BTN_LOAD                    1159
#define IDC_CHECK_RECYCLE               1160
#define IDC_INTERVAL                    1161
#define IDC_PROGRESS_TIME               1162
#define IDC_BTN_PRESCAN                 1163
#define IDC_BTN_SCAN                    1164
#define IDC_BTN_STOP                    1165
#define IDC_BTN_PAUSE                   1166
#define IDC_BTN_NEEDLE_NEW              1167
#define IDC_BTN_FINISHED                1168
#define IDC_COMBO_NEEDLE_ID             1169
#define IDC_SCROLLBAR_PUSH_DEPTH        1170
#define IDC_EDT_PUSH_DEPTH              1171
#define IDC_BTN_DEPTH_OK                1172
#define IDC_STATIC_DEPTH_MAX            1173
#define IDC_STATIC_DEPTH_MIN            1174
#define IDC_LIST_SERIES                 1175
#define IDC_RADIO_PROBE                 1176
#define IDC_RADIO_LAST_SCAN             1177
#define IDC_COMBO_PART                  1181
#define IDC_COMBO_PROTOCAL              1182
#define IDC_RADIO_PLANE1                1183
#define IDC_RADIO_PLANE2                1184
#define IDC_STATIC_NOTE                 1184
#define IDC_RADIO_PLANE3                1185
#define IDC_STATIC_NOTE2                1185
#define IDC_COMBO_BASE_INDEX            1187
#define IDC_SHOW_FIRST                  1190
#define IDC_SHOW_PRE                    1191
#define IDC_CHK_TARGETING               1191
#define IDC_SHOW_NEXT                   1192
#define IDC_RECYCLE                     1192
#define IDC_CYCLE                       1192
#define IDC_SHOW_LAST                   1193
#define IDC_EDIT1                       1193
#define IDC_EDT_INTERVALS               1193
#define IDC_EDT_OFFSET                  1193
#define IDC_EDIT_BASE                   1193
#define IDC_EDT_P_DESC                  1193
#define IDC_EDIT_IMAGE_NUMBER           1193
#define IDC_MRIOPTION_EDIT_INTERVAL     1193
#define IDC_EDIT_OFFSET                 1193
#define IDC_BTN_RECYCLE_OK              1194
#define IDC_EDT_LENGTH                  1194
#define IDC_EDIT_PHANTOM_REF            1194
#define IDC_EDT_OFFSET2                 1194
#define IDC_BTN_CHK_3D                  1194
#define ID_PLANNING_ADVANCED_OPTION     1195
#define IDC_BTN_CHK_FULL                1195
#define IDC_STATUS_BASE                 1196
#define IDC_STATUS_NEEDLE_PROBE         1197
#define IDC_STATIC_PLANE                1197
#define IDC_STATUS_PATIENT_TABLE        1198
#define IDC_STC_SEQUENCE                1198
#define IDC_STATIC_PLANNING             1199
#define IDC_STATIC_NEEDLE_PROBE         1200
#define IDC_CHECK_ADVANCED              1204
#define IDC_STATIC_INTERVAL             1205
#define IDC_STATIC_TIME_UNIT            1206
#define IDC_RADIO_PRE_SCANNING_PROBE    1207
#define IDC_RADIO_BIOPSY_PROBE          1208
#define IDC_STATIC_LENGTH               1210
#define IDC_STATIC_TYPE                 1211
#define IDC_STATIC_DIAMETER             1211
#define IDC_COMBO_PROBE_TYPE            1212
#define IDC_STATIC_UNIT_MM              1213
#define IDC_STATIC_UNIT_G               1214
#define IDC_RADIO_ON_SITE               1214
#define IDC_RADIO_Off_SITE              1215
#define IDC_STATIC_MIN                  1216
#define IDC_LBL_MIN                     1216
#define IDC_STATIC_MAX                  1217
#define IDC_LBL_MAX                     1217
#define IDC_BUTTON1                     1218
#define IDC_BUTTON_FILTER               1218
#define IDC_BTN_SYS                     1218
#define IDC_BTN_STATUS_BASE             1218
#define IDC_TEST                        1218
#define IDC_BTN_BASE_INDICATOR          1218
#define IDC_CMD_PROBE_SEL               1218
#define IDC_BTN_DEFAULT                 1218
#define IDC_BTN_BROW_F1                 1218
#define IDC_BTN_NEW                     1218
#define IDC_BUTTON_STANDARD             1218
#define IDC_BUTTON_IMPORT               1218
#define IDC_BUTTON_CLEAR                1218
#define IDC_BUTTON_TRACKING             1218
#define IDC_BUTTON_CLOSE                1218
#define IDC_BUTTON_DICOM                1218
#define IDC_BUTTON_QUIT                 1218
#define IDC_BUTTON_FUSION               1218
#define IDC_BTN_SERIES_DISPLAY          1219
#define IDC_BTN_STATUS_PROBE            1219
#define IDC_BTN_BROW_F2                 1219
#define IDC_BUTTON_CUT                  1219
#define IDC_BUTTON_DB                   1219
#define IDC_BTN_SYS2                    1220
#define IDC_BTN_BROW_F3                 1220
#define IDC_BUTTON_LOCAL                1220
#define IDC_STATIC_INDEX                1221
#define IDC_BTN_PAT                     1221
#define IDC_BTN_BROW_F4                 1221
#define IDC_BTN_SERIES                  1222
#define IDC_BTN_BROW_F5                 1222
#define IDC_BTN_PROBE                   1223
#define IDC_BTN_BROW_F6                 1223
#define IDC_BTN_ADVANCE                 1224
#define IDC_BTN_BROW_F7                 1224
#define IDC_SCAN_TIME                   1225
#define IDC_BTN_BROW_F8                 1225
#define IDC_CHK_MEASURE                 1226
#define IDC_BTN_BROW_F9                 1226
#define IDC_CHK_TARGET                  1227
#define IDC_BTN_BROW_PAGEDOWN           1227
#define IDC_BTN_BROW_PAGEUP             1228
#define IDC_CMP_LIST_SERIES             1229
#define IDC_BTN_BROW_QUIT               1229
#define IDC_BTN_BROW_PRT_SCR            1230
#define IDC_COMBO_BIOPROBE_TYPE         1231
#define IDC_RADIO_BASE_1                1232
#define IDC_RADIO_BASE_2                1233
#define IDC_RADIO_BASE_3                1234
#define IDC_RADIO_BASE_4                1235
#define IDC_FRM_PIC                     1236
#define IDC_COMBO1                      1237
#define IDC_COMBO2                      1238
#define IDC_COMBO3                      1239
#define IDC_COMBO4                      1242
#define IDC_PI_MSG                      1243
#define IDC_EDIT_PT_POS_SCAN            1244
#define IDC_EDIT_PT_POS_SURGERY         1246
#define IDC_RADIO1                      1247
#define IDC_RADIO_CALI_NOW              1247
#define IDC_MRIOPTION_RADIO_COR         1247
#define IDC_RADIO_REALTIP               1247
#define IDC_RADIO2                      1248
#define IDC_LST_SERIES                  1248
#define IDC_RADIO_CALI_MANUAL           1248
#define IDC_MRIOPTION_RADIO_SAG         1248
#define IDC_RADIO_VIRTUALTIP            1248
#define IDC_RADIO3                      1249
#define IDC_LBL_P_NAME                  1249
#define IDC_RADIO_CALI_LAST             1249
#define IDC_MRIOPTION_RADIO_AXI         1249
#define IDC_RADIO4                      1250
#define IDC_LBL_P_SEX                   1250
#define IDC_MRIOPTION_RADIO_PROBE_CENTER 1250
#define IDC_LBL_P_AGE                   1251
#define IDC_LBL_P_WEIGHT                1252
#define IDC_LBL_P_ID                    1254
#define IDC_CMD_ADVANCE                 1254
#define IDC_CMD_LOAD_TPS                1255
#define IDC_FRM_PATIENT                 1256
#define IDC_FRM_TPS                     1257
#define IDC_FRM_PROBE                   1258
#define IDC_LBL_PROTOCOL                1261
#define IDC_FRM_DLG                     1270
#define IDC_LBL_P_DESC                  1272
#define IDC_LBL_PUSHDEPTH               1273
#define IDC_LBL_UNIT                    1274
#define IDC_BTN_EXIT                    1275
#define IDC_CBO_MSG                     1276
#define IDC_LBL_MSG                     1278
#define IDC_EDT_BIO_LENGTH              1280
#define IDC_EDT_BIO_LENGTH2             1281
#define IDC_BTN_PHANTOM_INDICATOR       1281
#define IDC_PROGRESS_CALI               1282
#define IDC_PROGRESS_CALI_SCAN          1283
#define IDC_LABL_CALI_TIME              1284
#define IDC_BTN_PT_INDICATOR            1285
#define IDC_CMD_REDO                    1287
#define IDC_STATIC_POSITION             1288
#define IDC_STATIC_ORIENTATION          1289
#define IDC_STATIC_SWAP                 1290
#define IDC_CMD_SUB                     1291
#define IDC_CMD_ADD                     1292
#define IDC_CMD_SCROLL                  1293
#define IDC_BUTTON2                     1294
#define IDC_BUTTON_CONFIRM              1294
#define IDC_BUTTON_RECORD               1294
#define IDC_BTN_SUB_OFFSET              1294
#define IDC_STATIC_INFO                 1295
#define IDC_BTN_SELECT_PATIENT_LOCAL    1295
#define IDC_CMD_PRV                     1296
#define IDC_CMD_NXT                     1297
#define IDC_LST_INFO_HIST               1298
#define IDC_STATIC_VERSION              1299
#define IDC_STATIC_MSG                  1300
#define IDC_COMBO_CATEGORY              1301
#define IDC_LIST_CENTER                 1302
#define IDC_MRIOPTION_CHECK_CYCLE_SCAN  1302
#define IDC_LIST_LEFT                   1303
#define IDC_MRIOPTION_RADIO_MRI_CENTER  1303
#define IDC_LIST_RIGHT                  1304
#define IDC_MRIOPTION_EDIT_THICKNESS    1304
#define IDC_BTN_LEFT_UP                 1305
#define IDC_MRIOPTION_EDIT_GAP          1305
#define IDC_BTN_LEFT_DOWN               1306
#define IDC_MRIOPTION_EDIT_SLICE        1306
#define IDC_BTN_RIGHT_UP                1307
#define IDC_MRIOPTION_EDIT_NEX          1307
#define IDC_BTN_RIGHT_DOWN              1308
#define IDC_MRIOPTION_RADIO_PROBE       1308
#define IDC_BTN_LEFT_LEFT               1309
#define IDC_BTN_LEFT_RIGHT              1310
#define IDC_MRIOPTION_CHECK_NEW         1310
#define IDC_BTN_RIGHT_LEFT              1311
#define IDC_STATIC_PATIENT              1311
#define IDC_BTN_RIGHT_RIGHT             1312
#define IDC_BTN_REGISTER_PATIENT        1312
#define IDC_EDIT_PT_CUR_POS             1313
#define IDC_BUTTON_TRACK                1314
#define IDC_BUTTON_DICOMLIST            1314
#define IDC_BUTTON_CT_CALIBRATE         1315
#define IDC_BUTTON_SELECT               1317
#define IDC_BUTTON_SERIES               1318
#define IDC_BUTTON_CANCEL               1319
#define IDC_CHECK_POLYLINE              1320
#define IDC_CHECK_SAME_WWWL             1321
#define IDC_STATIC_WAITING              1322
#define IDC_BTN_SET_IMAGE_NUMBER        1323
#define IDC_STATIC_DISP                 1324
#define IDC_STATIC_CTRL                 1325
#define IDC_LIST_DICOM_LIST             1326
#define IDC_BUTTON_LOAD                 1327
#define IDC_STATIC_RESULT               1329
#define IDC_STATIC_ERROR                1330
#define IDC_STATIC_DISTANCE             1331
#define IDC_BUTTON_MANUAL               1331
#define IDC_BUTTON_CALIBRATE            1332
#define IDC_BTN_ADD_OFFSET              1334
#define IDC_BTN_SCROLL_OFFSET           1335
#define IDC_STATIC_OFFSET               1336
#define IDC_SLIDER1                     1339
#define IDC_SLIDER_DEPTH                1339
#define IDC_STATIC_VIEW                 1340
#define IDC_BUTTON_VIEW_AV              1341
#define IDC_BUTTON_VIEW_ASVP            1342
#define IDC_BUTTON_VIEW_AVT             1343
#define IDC_BUTTON_VIEW_AST             1343
#define IDC_BUTTON_VIEW_AVVT            1344
#define IDC_BUTTON_VIEW_TAPV            1344
#define IDC_CHECK_SHOW_FUSION           1345
#define IDC_BUTTON_SELECT_FUSION        1346
#define IDC_LIST_PNT                    1347
#define ID_CONFIRM                      1348
#define IDC_BUTTON_FREEZE               1349
#define IDC_STATIC_PROBE                1350
#define ID_CONTROL_CALI_MRI2PT          32772
#define ID_CONTROL_CONFIG               32773
#define ID_CONTROL_CALI_PROBE           32775
#define ID_CONTROL_COM_SET              32776
#define ID_CONTROL_CONNECT_NDI          32777
#define ID_SYSTEM_NDI_SYSTEM            32778
#define ID_SYSTEM_TRACKING              32779
#define ID_SYSTEM_TOOL                  32780
#define ID_CONTROL_ACTIVE_TOOL          32781
#define ID_SURGERY_CRYOTHERAPY          32782
#define ID_VIEW_DISPLAY_MANUAL          32784
#define ID_VIEW_DISPLAY_TRACKING        32785
#define ID_FILE_OPEN_MRI_SERIES         32786
#define IDC_POPUP1_CHANGE_IMG_COORD     32787
#define ID_FILE_IMPORT_RECT_POS         32788
#define ID_FILE_EXPORT_MRI_POS          32789
#define ID_PROBE_SIMULATE               32790
#define ID_PROBE_STOP_SIMULATE          32792
#define ID_PROBE_SIMULATE_POP_DLG       32793
#define ID_SYSTEM_VOLUME_STANDARD       32794
#define ID_SYSTEM_VOLUME_PYRAMID        32795
#define ID_SUGERY_PRE_SUGERY_CALI       32796
#define ID_SURGERY_SURGERY              32797
#define ID_SUGERY_SUGERY_CALI           32798
#define ID_CONTROL_CONNECT_SERVER       32799
#define ID_FILE_EXPORT_PHANTOM2PT       32800
#define ID_FILE_IMPORT_PHANTOM2PT       32801
#define ID_FILE_IMPORT_MRI2PT           32802
#define ID_FILE_EXPORT_MRI2PT           32803
#define ID_FILE_IMPORT_PRE_CALI         32804
#define ID_FILE_EXPORT_PRE_CALI         32805
#define ID_FILE_EXPORT_MRI2PHANTOM      32806
#define ID_FILE_IMPORT_MRI2PHANTOM      32807
#define ID_FILE_IMPORT_PT2TRACK         32808
#define ID_FILE_EXPORT_PT2TRACK         32809
#define POPUP1_DISP_1                   32810
#define POPUP1_DISP_2                   32811
#define POPUP1_DISP_3                   32812
#define ID_FILE_IMPORT_PHANTOM_PATTERN  32813
#define ID_FILE_EXPORT_PHANTOM_PATTERN  32814
#define ID_SURGERY_PHANTOM_CALI         32815
#define ID_SURGERY_BASE_CALI            32816
#define ID_FILE_IMPORT_BASE             32817
#define ID_FILE_EXPORT_BASE             32818
#define POPUP1_DISP_3D                  32819
#define ID_MRI_PLAY                     32820
#define ID_MRI_STOP                     32821
#define ID_SYSTEM_CONFIG                32822
#define ID_MRI_PAUSE                    32823
#define ID_MRI_FORWARD                  32824
#define ID_MRI_BACKWARD                 32825
#define ID_FILE_IMPORT_MRI_PHANTOM_POINT 32826
#define ID_FILE_EXPORT_MRI_PHANTOM_POINT 32827
#define ID_FILE_IMPORT_BASE2PT2         32828
#define ID_FILE_EXPORT_BASE2PT2         32829
#define ID_FILE_IMPORT_PT2BASE1         32830
#define ID_FILE_EXPORT_PT2BASE1         32831
#define ID_CONTROL_DISCONNECT_MRI       32832
#define POPUP2_GET_DISTANCE_TO_PHANTOM_CENTER 32833
#define ID_VIEW_WINDOW_1                32835
#define ID_VIEW_WINDOW_22               32836
#define ID_VIEW_WINDOW_13               32837
#define ID_TOOL_DISTANCE                32838
#define ID_SPOPUP_CLEAR_DIST            32839
#define ID_SP_PLANNING                  32840
#define ID_FILE_IMPORT_MODEL            32841
#define ID_POPUP_PROBE_SHOW_LINE_TO_VTARGET 32842
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER 32843
#define ID_TOOL_TRACKING                32844
#define ID_POPUP_PROBE_SHOW_DIST_TIP_TO_TARGET 32845
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_1 32846
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_2 32847
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_3 32848
#define ID_SPOPUP_UPDATE                32849
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_1_SWAP 32850
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_2_SWAP 32851
#define ID_POPUP_PROBE_CONTROL_MRI_SCANNER_SCAN_PLANE_3_SWAP 32852
#define ID_SPOPUP_RESET_EYE             32853
#define ID_MENUITEM32855                32855
#define ID_MENUITEM32856                32856
#define ID_MENUITEM32857                32857
#define ID_a                            32859
#define ID_FILE_IMPORT_SERIES           32862
#define ID_FILE_EXIT                    32864
#define ID_VIEW_FRAME_FOUR_2D           32865
#define ID_VIEW_THREE2D_ONE3D_LEFT_TOP  32866
#define ID_VIEW_THREE2D_ONE3D_TOP       32867
#define ID_VIEW_ONE3D                   32868
#define ID_CALIBRATION_MRI              32869
#define ID_CALIBRATION_CAMERA           32870
#define ID_CALIBRATION_PATIENT_TABLE    32871
#define ID_CALIBRATION_NEEDLE_PROBE     32872
#define ID_APPLICATION_BIOPSY           32873
#define ID_APPLICATION_CRYOTHERAPY      32874
#define ID_APPLICATION_BRACHYTHERAPY    32875
#define ID_APPLICATION_OZONETHERAPY     32876
#define ID_TOOLS_CONFIGURATIONS         32877
#define ID_HELP_ABOUT                   32878
#define POPUP1_DISP_2D_ONE              32879
#define POPUP1_DISP_2D_TWO              32880
#define POPUP1_DISP_2D_THREE            32881
#define POPUP1_DISP_2D_FOUR             32882
#define ID_CALIBRATION_HOLDER           32886
#define POPUP1_SERIES_DEL               32887
#define ID_POPUP_SHOWIMGLEGEND          32888
#define ID_BUTTON32889                  32889
#define ID_FILE_OPEN_DATABASE           32890
#define ID_DEBUG_CONNECT_MRI            32891
#define ID_MANUAL_CALIBRATION           32892
#define ID_POPUP_SELECT                 32893
#define ID_SYS_IMPORT_SERIES            32894
#define ID_SYS_OPEN_DB                  32895
#define ID_SYS_EXIT                     32896
#define ID_SYS_ABOUT                    32897
#define ID_DD_TEST                      32904
#define ID_PROT_SUB_1                   32905
#define ID_POPUP_TARGET_SEL             32906
#define ID_POPUP_TARGET_DEL             32907
#define ID_SYS_CALI_PT                  32908
#define ID_DEBUG_VIEW_TO_PROBE          32909
#define ID_SYS_CONNECT_CAM              32910
#define ID_RPOBE_SUB_1                  32911
#define ID_SYS_CONNECT_MRI              32912
#define IDM_BROWSE_ADD_COLUMN           32913
#define ID_SPOPUP_SETUP_LEGEND          32913
#define IDM_BROWSE_DELETE_COLUMN        32914
#define ID_SPOPUP_WINDOWLEVEL_PF        32915
#define IDM_BROWSE_ADD_ROW              32915
#define ID_SPOPUP_WINDOWLEVEL_BRAIN     32916
#define IDM_BROWSE_DELETE_ROW           32916
#define ID_SPOPUP_WINDOWLEVEL_IAC       32917
#define ID_SPOPUP_WINDOWLEVEL_BONE      32918
#define ID_SPOPUP_WINDOWLEVEL_LUNG      32919
#define ID_SPOPUP_WINDOWLEVEL_ABDOMEN   32920
#define ID_SPOPUP_WINDOWLEVEL_LIVERA    32921
#define ID_SPOPUP_WINDOWLEVEL_LIVERB    32922
#define ID_SPOPUP_WINDOWLEVEL_SPINE     32923
#define ID_SPOPUP_WINDOWLEVEL_FAT       32924
#define ID_SPOPUP_RESET_WINDOWLEVEL     32925
#define ID_SYS_START_MONITOR            32926
#define ID_SYS_CALI_TUNE                32927
#define ID_SYS_CALI_MANUAL_SHIM         32928
#define ID_SYS_CALI_RESTORE_SHIM        32929
#define ID_SYS_SURGERY_WIZARD           32930
#define ID_SPOPUP_COLOR_IMAGE           32932
#define ID_SYS_FUSION_IMAGE             32933
#define ID_STAGE_OF_THERAPY             61204
#define ID_DELETE_TARGET_NOTE           61205
#define ID_DELETE_TARGET_CAPTION        61206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        364
#define _APS_NEXT_COMMAND_VALUE         32934
#define _APS_NEXT_CONTROL_VALUE         1351
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
